plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  

theme: jekyll-theme-slate
### tactile looks good with alot of text, but 
### because the links are red in this resource, it is too much
# ---------------------------
# theme: jekyll-theme-tactile

