---
title: 'R Resource Compendium'
author: "E Bryan Crenshaw III"
date: "November 2, 2014"
output: 
  html_document:
    keep_md: true
---

### Overall Resources  

- [R for Data Science](https://r4ds.had.co.nz/)  
- [Quick-R](http://www.statmethods.net)  
- [Field Guide to the R Ecosystem](http://fg2re.sellorm.com/)  
- [Advanced R](http://adv-r.had.co.nz/)  
- [ComputerWorld: Beginner's guide to R](http://www.computerworld.com/article/2497143/business-intelligence-beginner-s-guide-to-r-introduction.html)  
- [R Bootcamp](http://jaredknowles.com/r-bootcamp/)  
- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)  
- [Efficient R Programming](https://csgillespie.github.io/efficientR/)  
- [R Tutorial: An R Introduction to Statistics](http://www.r-tutor.com) - Statistics eBook written with R in mind  
- [Learning R](http://www.amazon.com/Learning-R-Richard-Cotton/dp/1449357105) - Textbook  

### Topical Resources

- [Data Import](http://www.r-tutor.com/r-introduction/data-frame/data-import)  
- Data Visualization with R
    - [Workshop: Bubble plots, Hexbin plots, Visualizing contingency tables, Visual inference , and Presentation of statistical results](https://www.mzes.uni-mannheim.de/socialsciencedatalab/article/datavis/)  
    - [Graphics for communication: Chapter 28 R for Data Science](https://r4ds.had.co.nz/graphics-for-communication.html)  
    - [Beautiful plotting in R: A ggplot2 cheatsheet](http://zevross.com/blog/2014/08/04/beautiful-plotting-in-r-a-ggplot2-cheatsheet-3/)  
    - [Creating publication-quality graphs with ggplot2](https://wilkelab.org/practicalgg/)
    - [Map Plots Created With R And Ggmap - A Tutorial](https://www.littlemissdata.com/blog/maps)
    - [Simple Graphs with R](http://www.harding.edu/fmccown/r/)  
    - [timevis: An R package for creating timeline visualizations](https://daattali.com/shiny/timevis-demo/)  
- [Databases using R](https://db.rstudio.com/)
- [Dates - Format dates using strftime() crib sheet](https://jeffkayser.com/projects/date-format-string-composer/index.html)  
- [Descriptive Statistics](http://www.statmethods.net/stats/descriptives.html) 
- EDA Packages
    - [summarytools](https://www.r-bloggers.com/easily-explore-your-data-using-the-summarytools-package/)  
    - [funModeling](https://www.r-bloggers.com/exploratory-data-analysis-data-preparation-with-funmodeling-2/)
- GIS/Geocomputation
  - [Earth Analytics Course: Learn Data Science](https://www.earthdatascience.org/courses/earth-analytics/)  
  - [Geocomputation with R](https://geocompr.robinlovelace.net/)
  - [Leaflet for R](https://rstudio.github.io/leaflet/)  
  - [Visualising your hiking trails and photos with My Tracks, R and Leaflet](http://archived.mhermans.net/hiking-gpx-r-leaflet.html)
  - [GPX overview: An R function to create an overview of your .gpx files (using leaflet and RgoogleMaps)](https://digital-geography.com/gpx-overview-r-function-create-overview-gpx-files-using-leaflet-rgooglemaps/) 
  - [Plotting GPS tracks with R](https://rpubs.com/ials2un/gpx1) 
- [Using R with Jupyter Notebooks](http://blog.revolutionanalytics.com/2015/09/using-r-with-jupyter-notebooks.html)  
- Machine Learning
  - [Clustering: How to Perform Hierarchical Clustering using R](https://www.r-bloggers.com/how-to-perform-hierarchical-clustering-using-r/) 
- Packages
  - [Writing Frictionless R Package Wrappers — Introduction](https://rud.is/b/2020/01/01/writing-frictionless-r-package-wrappers-introduction/) 
  - [pkgdown](https://pkgdown.r-lib.org/) - `pkgdown` is designed to make it quick and easy to build a website for your package. 
- [Regular Expression Language - Quick Reference](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference) 
- `reticulate`
  - [`R` you ready for python (gentle introduction to reticulate package)'](https://notast.netlify.com/post/r-you-ready-for-python-gentle-introduction-to-reticulate-package/) - Several links in this page for other uses of R and Python together, including:
    - [R for data wrangling and pre-processing and python via reticulate to do some prediction](https://www.statworx.com/de/blog/r-and-python-using-reticulate-to-get-the-best-of-both-worlds/)  
    - [Using python again via reticulate to do some prediction and used R’s almighty ggplot to visualize the results](https://heads0rtai1s.github.io/2019/10/03/reticulate-intro/)  
  - [The reticulate package solves the hardest problem in data science: people](https://rviews.rstudio.com/2019/03/18/the-reticulate-package-solves-the-hardest-problem-in-data-science-people/)  
  - [reticulate GitHub site](https://github.com/rstudio/reticulate) - there are different ways to use R and Python interactivel. Check reticulate’s github site to see which one suits you best.
- RStudio - [See below](#rstudio)  
- shiny
    - [Shinyapps.io - Getting started](https://shiny.rstudio.com/articles/shinyapps.html) 
    - [Persistent data storage in Shiny apps](https://shiny.rstudio.com/articles/persistent-data-storage.html)  
- Slides/Presentations 
  - Powerpoint  
    - [Make PowerPoint Presentations with R Markdown](https://resources.rstudio.com/webinars/make-powerpoint-presentations-with-r-markdown-nathan-stephens) - A good introductory video, but a bit long. 
    - [Rendering PowerPoint Presentations with RStudio](https://support.rstudio.com/hc/en-us/articles/360004672913)  
    - [Render PowerPoint presentations from R Markdown documents: Examples on GitHub](https://github.com/sol-eng/powerpoint/tree/master/examples)  
    - [Powerpoint Section in `R Markdown: The Definitive Guide`](https://bookdown.org/yihui/rmarkdown/powerpoint-presentation.html)  
    - [How to Make a PowerPoint Template](https://www.wikihow.com/Make-a-PowerPoint-Template) 
  - Xaringan
    - [Xaringan Google Search](https://www.google.com/search?client=firefox-b-1-d&q=xaringan)  
    - [xaringan Presentations - R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/xaringan.html)  
    - [Make Your Presentations Fun in Xaringan](http://svmiller.com/blog/2018/02/r-markdown-xaringan-theme/)  
- Websites/Blogs
    - [How I set up my first website (again)](https://notast.netlify.com/post/blogdown-hugo-git-github-netlify-rss-disqus/)  
    - Specific to R Markdown
        - [GitHub and RStudio](https://resources.github.com/whitepapers/github-and-rstudio/) - This tutorial teaches you to create R Markdown documents with RStudio and publish them via GitHub, using GitHub Pages.  
        - ["GitHub Pages" using `blogdown`](https://bookdown.org/yihui/blogdown/github-pages.html) - Parts that deal directly with GitHub Pages  
        - [blogdown: Creating Websites with R Markdown](https://bookdown.org/yihui/blogdown/) - Entire blogdown overview.  
          - [1.2 A quick example](https://bookdown.org/yihui/blogdown/a-quick-example.html)
        - [How I started a blog based on blogdown: A walkthrough](https://rcrastinate.rbind.io/post/how-to-start-a-blog-based-on-blogdown-a-walkthrough/)   
        - [share-blogdown](https://github.com/apreshill/share-blogdown) - This is a demo course website made with the blogdown R package and a custom Academic theme for Hugo. This website was made as part of an RStudio Webinar.
    - General Approaches
        - [HUGO](https://gohugo.io/) - The world’s fastest framework for building websites.  
        - [Academic](https://sourcethemes.com/academic/) - Source of themes for RMd, such as [Maya Gans](https://maya.rbind.io/).  
        - [Hugo Academic Theme repo](https://github.com/gcushen/hugo-academic) - The website builder for Hugo. Build and deploy a beautiful website in minutes!   [https://sourcethemes.com/academic/](https://sourcethemes.com/academic/)  
        - [Hugo vs. Jekyll: Comparing the leading static website generators](https://opensource.com/article/17/5/hugo-vs-jekyll)  
        - [Getting started with Jekyll, a free and open source static site generator](https://opensource.com/article/17/4/getting-started-jekyll) 
    - GitHub Pages
        - [What is GitHub Pages? Websites for you and your projects.](https://pages.github.com/)
        - [Getting Started with GitHub Pages](https://guides.github.com/features/pages/) 
        - [Creating and Hosting a Personal Site on GitHub](http://jmcglone.com/guides/github-pages/) - A step-by-step beginner's guide to creating a personal website and blog using Jekyll and hosting it for free using GitHub Pages.  
        - [Easy Markdown to Github Pages](https://nicolas-van.github.io/easy-markdown-to-github-pages/)  - Convert Markdown files in Github to a full website using Github Pages.
    
 
 

#### Specific Commands

- [Barplot - basic examples](http://www.statmethods.net/graphs/bar.html)
- [beeswarm graph command](http://www.cbs.dtu.dk/~eklund/beeswarm/)
- [dput example](http://stackoverflow.com/questions/15865112/r-find-matching-columns-in-two-data-frames-for-t-test-statistics-r-beginner)
- Graphs
    - [ggplot2 graph colors](http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/)
    - [Conditional colors: Setting colours in ggplot conditional on value](https://community.rstudio.com/t/setting-colours-in-ggplot-conditional-on-value/8328)
    - [How to add values on bar of grouped bar plot](http://stackoverflow.com/questions/11911506/how-to-add-values-on-bar-of-grouped-bar-plot-using-mtext)
    - [Basics of Histograms](http://www.r-bloggers.com/basics-of-histograms/)
    - [Plotting distributions (ggplot2)](http://www.cookbook-r.com/Graphs/Plotting_distributions_(ggplot2)/)  
    - [Plotting means and error bars (ggplot2)](http://www.cookbook-r.com/Graphs/Plotting_means_and_error_bars_(ggplot2)/)  
    - [Viridis colour scales - provide colour maps that are perceptually uniform in both colour and black-and-white.](https://ggplot2.tidyverse.org/reference/scale_viridis.html)  
- Inputs
    - [Input from console](http://stackoverflow.com/questions/5974967/what-is-the-correct-way-to-ask-for-user-input-in-an-r-program)
  - [knitr: Working with subdirectories](https://stackoverflow.com/questions/24585254/working-with-knitr-using-subdirectories)  
- [pins: Pin, Discover and Share Resources](http://pins.rstudio.com/)  
- Rows - [preallocoation vs rbind](http://stackoverflow.com/questions/20689650/how-to-append-rows-to-an-r-data-frame)
-  Rows - [insertRow](http://stackoverflow.com/questions/11561856/add-new-row-to-dataframe)
- Slidify Package - [starting](http://slidify.org/start.html)
- Slidify Package - [title page color change in Stack Overflow](http://stackoverflow.com/questions/20875593/how-to-control-the-background-color-of-the-first-slidify-slide)
- [Sorting - basics](http://www.dummies.com/how-to/content/how-to-sort-data-frames-in-r.html)
- [Introduction to stringr](https://cran.r-project.org/web/packages/stringr/vignettes/stringr.html)  
- [t-test general intro](http://statistics.berkeley.edu/computing/r-t-tests)
- [t-test on 2 data frames after finding matching columns](http://stackoverflow.com/questions/15865112/r-find-matching-columns-in-two-data-frames-for-t-test-statistics-r-beginner)
- [Venn Diagrams](http://rstudio-pubs-static.s3.amazonaws.com/13301_6641d73cfac741a59c0a851feb99e98b.html)


Packages  
- [slider](https://github.com/DavisVaughan/slider) - provides a family of general purpose “sliding window” functions. The goal of these functions is usually to compute rolling averages, cumulative sums, rolling regressions, or other “window” based computations.  

#### Solving Specific Problems

- [R - list to data frame](https://stackoverflow.com/questions/4227223/r-list-to-data-frame)
- [R can API and So Can You! - Using plumbR to make API, and how to dockerize it](https://medium.com/@heathernolis/r-can-api-c184951a24a3)  
- [RStudio 1.2 Preview: Plumber Integration](https://blog.rstudio.com/2018/10/23/rstudio-1-2-preview-plumber-integration/) 
- [Scraping web data about Australian politicians with RSelenium](https://www.r-bloggers.com/scrapping-data-about-australian-politicians-with-rselenium/)
- [Adding themes and logo to ggplot graphs](https://michaeltoth.me/you-need-to-start-branding-your-graphs-heres-how-with-ggplot.html)   
- [Color picker for data](http://tristen.ca/hcl-picker/#/hlc/6/1/15534C/E2E062) 

#### RStudio {#rstudio}

- [R Studio Blog: Archives](https://blog.rstudio.com/archives/)  
- [Addins - Instructions](https://rstudio.github.io/rstudioaddins/)  
- Libraries Folder - Find using `.libPaths()`
- [snippets](https://support.rstudio.com/hc/en-us/articles/204463668-Code-Snippets)  
- [Using the RStudio IDE](https://support.rstudio.com/hc/en-us/sections/200107586-Using-the-RStudio-IDE)  
- Themes
  - [Yule RStudio](https://github.com/gadenbuie/yule-rstudio)  
- [Version Control with RStudio](https://support.rstudio.com/hc/en-us/articles/200532077-Version-Control-with-Git-and-SVN)  

#### Examples of R in Action

- [Facebook Data Geeks Using ggplot2 stat_smooth](https://www.theatlantic.com/technology/archive/2014/02/when-you-fall-in-love-this-is-what-facebook-sees/283865/)
- [Looking at Prices in the ACA Exchanges, including link to code on Github](http://www.paulmichaelcohen.com/competition-and-price-on-the-federal-health-exchange-marketplace/)

<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
